# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  GO111MODULE: off

jobs:
  test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.2', '1.3', '1.4', '1.5', '1.6', '1.7', '1.8', '1.9', '1.10', '1.11', '1.12', '1.13', '1.14', '1.15', '1.16', '1.17', '1.18' ]
    name: Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: go test -v ./...
    - run: go test -coverprofile=coverage.txt ./...
      if: matrix.go == '1.18'
    - uses: codecov/codecov-action@v3.1.1
      if: matrix.go == '1.18'
      with:
        file: ./coverage.txt
